# Generated by Django 2.2.5 on 2019-10-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miasto',
            name='kod',
            field=models.CharField(help_text='Wpisz kod pocztowy', max_length=30),
        ),
        migrations.AlterField(
            model_name='miasto',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='miasto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dochod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='imie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='roks',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='uczelnia',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='uczelnia'),
        ),
    ]
