# Generated by Django 2.2.5 on 2019-10-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20191003_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='jarski',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeżeli składnik jest odpowiedni dla wegetarian', verbose_name='jarski?'),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='składnik'),
        ),
    ]
